### ISSUE TITLE
Catch up on the upstream, 英語版に追従する

### ISSUE THREAD

**Issue by ysaito8015** [appliedepi/epiRhandbook_jp#105]
To catch up on the English edition.
日本語版を英語版の更新記事に追従する

## Catch Up On The...
追従するバージョン

### Version

| Date | Major changes |
|-----|-----|
| 20 Nov 2022 | Release of version 1.0.1 |

### Render date

```r
##  tz       Europe/Berlin
##  date     2022-12-13
```

[upstream commit](0f1cbf2512081dbffa2066afb8f39be2acb3056e)

## Major Changes
主要な変更点

- Update to R version 4.2
- Data cleaning: switched {linelist} to {matchmaker}, removed unnecessary line from `case_when()` example
- Dates: switched {linelist} `guess_date()` to {parsedate} `parse_date()`
- Pivoting: slight update to `pivot_wider()` `id_cols=`
- Survey analysis: switched `plot_age_pyramid()` to `age_pyramid()`, slight change to alluvial plot code
- Heat plots: added `ungroup()` to `agg_weeks` chunk
- Interactive plots: added `ungroup()` to chunk that makes `agg_weeks` so that `expand()` works as intended
- Time series: added [`data.frame()`](https://rdrr.io/r/base/data.frame.html) around objects within all [`trending::fit()`](https://rdrr.io/pkg/trending/man/fit.html) and [`predict()`](https://rdrr.io/r/stats/predict.html) commands
- Combinations analysis: Switch `case_when()` to [`ifelse()`](https://rdrr.io/r/base/ifelse.html) and added optional `across()` code for preparing the data
- Transmission chains: Update to more recent version of {epicontacts}

## ToDo

変更点が多いので細かく作業とイシューで分ける

- [x] Update scripts -> https://github.com/appliedepi/epiRhandbook_jp/issues/106
    - Enable `.renv`
    -  Update LICENSE.md, README.md
    - Update files related bookdown build
- [x] Replace GitHub repository links from old, (https://github.com/epirhandbook/Epi_R_handbook) to new, (https://github.com/appliedepi/epiRhandbook_eng) https://github.com/appliedepi/epiRhandbook_jp/issues/108
- [x] Update contents -> https://github.com/appliedepi/epiRhandbook_jp/issues/110
    - ./data/
    - index.Rmd
    - ./new_pages

見つけたら記入する

## Setting epiRhandbook_eng as Upstream at Local
epiRhandbook_eng をローカルで upstream として登録して, 差分を比較する方法

```shell
# 新規にリポジトリをクローンする
$ git clone https://github.com/appliedepi/epiRhandbook_jp ./epiRhandbook_jp-check && cd $_
$ git remote add upstream git@github.com:appliedepi/epiRhandbook_eng.git
$ git fetch upstream
# 英語版追跡専用のローカルブランチを作成する
$ git checkout master && git checkout -b eng_master
# 翻訳はじめの直前のコミットに戻る
# https://github.com/appliedepi/epiRhandbook_jp/commit/cf1410106df7bbf19e9b2b266d90c1eadcf949a3
$ git reset --hard cf1410106df7bbf19e9b2b266d90c1eadcf949a3
# bookdown で生成されたファイル群は削除しておく
$ rm -rf ./_bookdown_files
$ rm ./_main.Rmd
$ rm -rf ./html_outputs
# バイナリファイルでマージに失敗するファイルを予め削除しておく
$ rm ./data/case_linelists/linelist_cleaned.xlsx
$ rm ./images/R\ Handbook\ Logo.png
$ rm ./images/R_data_structures.png
$ git add . && git commit -m'Remove outputs and binary files' # 削除した状態でコミットしておく
# 全く別のリポジトリをマージするので特別なオプションを追加してマージする
$ git merge upstream/master --allow-unrelated-histories
# 差分チェックのノイズになるファイルは削除する
# epiRhandbook_jp リポジトリは git filter-repo したのでサイズの大きなファイルなどは削除されている
$ git rm -rf _bookdown_files
$ git rm _main.Rmd
$ git rm -rf bookdown
$ git rm -rf preview
$ git rm -rf html_outputs
$ git rm images/Handbook\ Logo\ PPT.pptx
$ git rm images/R\ Handbook\ Logo.png
$ git rm images/R\ Handbook\ Logo-DESKTOP-JIEMMI.png
$ git rm images/R_data_structures-DESKTOP-JIEUMMI.png
$ git rm new_pages/interactive_plots.html
$ git rm new_pages/sampling.rmd
$ git rm offline_long/Epi_R_Handbook_offline.html
# マージの途中でコンフリクトが起こるので解決しておく
$ vim .gitignore LICENSE.md README.md _bookdown.yml _output.yml _small_bookdown.yml bookdown_runfile.R common.R data/make_evd_dataset.R index.Rmd new_pages/age_pyramid.Rmd new_pages/basics.Rmd new_pages/characters_strings.Rmd new_pages/cleaning.Rmd new_pages/collaboration.Rmd new_pages/combination_analysis.Rmd new_pages/data_used.Rmd new_pages/dates.Rmd new_pages/descriptive_statistics.Rmd new_pages/diagrams.Rmd new_pages/editorial_style.Rmd new_pages/epicurves.Rmd new_pages/epidemic_models.Rmd new_pages/factors.Rmd new_pages/flexdashboard.Rmd new_pages/ggplot_basics.Rmd new_pages/ggplot_basics_old.Rmd new_pages/ggplot_tips.Rmd new_pages/gis.Rmd new_pages/grouping.Rmd new_pages/heatmaps.Rmd new_pages/interactive_plots.Rmd new_pages/iteration.Rmd new_pages/joining_matching.Rmd new_pages/missing_data.Rmd new_pages/moving_average.Rmd new_pages/phylogenetic_trees.Rmd new_pages/pivoting.Rmd new_pages/plot_continuous.Rmd new_pages/plot_discrete.Rmd new_pages/regression.Rmd new_pages/relational_databases.Rmd new_pages/standardization.Rmd new_pages/stat_tests.Rmd new_pages/survey_analysis.Rmd new_pages/time_series.Rmd new_pages/transmission_chains.Rmd
# コンフリクト解決後にマージコミットを作成
$ git add -i # コンフリクトを解決したファイルを追加する
$ git commit -m'Catch up on the upstream'
# ひとつ前のコミット (merge 直前のコミット)と diff をとる
$ git diff HEAD^
```

**Comment by ysaito8015** [comment]
Hi @nsbatra 
We update the html_outputs to catch up on the English version.
Could you update the Japanese website? Thank you!

Cc. @hitomik723 @ironwest

**Comment by nsbatra** [comment]
@ysaito8015 The website has been updated. Please let me know if anything looks incorrect.
Thank you very much for your attention to the updates!

cc @aspina7
